const SET_FILES_BY_FOLDER_ID = "filesByFolderId";
const SET_SELECTED_FILE = "setSelectedFile";
const ADD_FILE = 'ADD_FILE';
const DELETE_FILE = 'DELETE_FILE';


export { SET_FILES_BY_FOLDER_ID, SET_SELECTED_FILE, ADD_FILE,DELETE_FILE };